name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-11-jdk
          pip3 install buildozer cython

      - name: Build APK
        run: |
          sudo apt install -y git zip unzip curl python3 python3-pip python3-setuptools
          pip3 install buildozer
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: bin/*.apk
